name: Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    # 빌드 후 gh-pages에 배포한다.
    steps:
      - name: Check out Repository
        uses: actions/checkout@v3
        with:
          persist-credentials: false

      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Initialize global dependencies
        run: npm install -g cross-env vite

      - name: Install dependencies
        run: npm install

      - name: Server dir install dependencies
        working-directory: ./server
        run: npm install

      - name: Build
        run: tsc -b && cross-env NODE_ENV=production vite build --mode=production
        env:
          VITE_BRAND: ${{ variables.VITE_BRAND }}
          VITE_BLOG: ${{ variables.VITE_BLOG }}
          VITE_GITHUB: ${{ variables.VITE_GITHUB }}
          VITE_DEPLOY_PATH: ${{ variables.VITE_DEPLOY_PATH }}
          VITE_DEFAULT_COVER: ${{ variables.VITE_DEFAULT_COVER }}

      - name: Build Server
        working-directory: ./server
        run: npm run build

      - name: Create nojekyll
        working-directory: ./dist
        run: touch .nojekyll

      - name: Deploy to gh-pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GH_TOKEN }}
          publish_dir: ./dist
          publish_branch: gh-pages
